# Numpy Intro 

In [1]:
import numpy as np

## Creating Arrays


In [2]:
zerros_array = np.zeros(3)
zerros_array

array([0., 0., 0.])

In [4]:
ones_array = np.ones(3)
ones_array

array([1., 1., 1.])

In [5]:
constant_array = np.full(3, 28)
constant_array

array([28, 28, 28])

In [8]:
# Can also convert List to Arrays
my_list = [1,2,3,5]

list_to_array = np.array(my_list)

list_to_array

array([1, 2, 3, 5])

In [11]:
# Generating Range of Numbers 
range_array = np.arange(10)  #from 0 to 9
range_array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [17]:
#Create Arrays with linear spacing
linear_spacing_array = np.linspace(0,10,11) #from 0 to 10, with 11 elements
linear_spacing_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Multi-Dimensional Arrays
### Multidimensional arrays are matrices - Numpy does that

In [25]:
zeros_matrix = np.zeros((4,3))
zeros_matrix

ones_matrix = np.ones((4,3))
ones_matrix

identity_matrix = np.eye(4)
identity_matrix

constant_matrix = np.full((4,3), 28)
constant_matrix

array([[28, 28, 28],
       [28, 28, 28],
       [28, 28, 28],
       [28, 28, 28]])

## Indexing and Slicing Arrays - To access elements in numpy arrays using index and slicing

In [32]:
arr = np.array(([2,3,4], [5,6,7])); print(arr)
first_row = arr[0,:]; print("indexing the first row", first_row)
second_column = arr[:,1]; print("slicing the second column", second_column)

[[2 3 4]
 [5 6 7]]
indexing the first row [2 3 4]
slicing the second column [3 6]


In [34]:
list2 = ([2,3,4], [5,6,7], [8,9,10])
list2_matrix = np.array(list2)
list2_matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Randomly Generated Arrays 
### Arrays filled with random numbers. Need to set seed for reproducibility 

In [36]:
np.random.seed(1)
random_array = np.random.rand(5,2) #generates random numbers between 0,1
random_array

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

## Element Wise Operations 

### Comparison Operators

### Logical Operators

## Summarizing Operations