# Numpy Intro 

In [1]:
import numpy as np

## Creating Arrays


In [2]:
zerros_array = np.zeros(3)
zerros_array

array([0., 0., 0.])

In [3]:
ones_array = np.ones(3)
ones_array

array([1., 1., 1.])

In [4]:
constant_array = np.full(3, 28)
constant_array

array([28, 28, 28])

In [5]:
# Can also convert List to Arrays
my_list = [1,2,3,5]

list_to_array = np.array(my_list)

list_to_array

array([1, 2, 3, 5])

In [39]:
# Generating Range of Numbers 
range_array = np.arange(10)  #from 0 to 9
print(range_array)

np.arange(1,10,2) #from 1  to 10 spaced by 2

[0 1 2 3 4 5 6 7 8 9]


array([1, 3, 5, 7, 9])

In [7]:
#Create Arrays with linear spacing
linear_spacing_array = np.linspace(0,10,11) #from 0 to 10, with 11 elements
linear_spacing_array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

## Multi-Dimensional Arrays
### Multidimensional arrays are matrices - Numpy does that

In [8]:
zeros_matrix = np.zeros((4,3))
zeros_matrix

ones_matrix = np.ones((4,3))
ones_matrix

identity_matrix = np.eye(4)
identity_matrix

constant_matrix = np.full((4,3), 28)
constant_matrix

array([[28, 28, 28],
       [28, 28, 28],
       [28, 28, 28],
       [28, 28, 28]])

## Indexing and Slicing Arrays - To access elements in numpy arrays using index and slicing

In [9]:
arr = np.array(([2,3,4], [5,6,7])); print(arr)
first_row = arr[0,:]; print("indexing the first row", first_row)
second_column = arr[:,1]; print("slicing the second column", second_column)

[[2 3 4]
 [5 6 7]]
indexing the first row [2 3 4]
slicing the second column [3 6]


In [10]:
list2 = ([2,3,4], [5,6,7], [8,9,10])
list2_matrix = np.array(list2)
list2_matrix

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## Randomly Generated Arrays 
### Arrays filled with random numbers. Need to set seed for reproducibility 

In [11]:
np.random.seed(1)
random_array = np.random.rand(5,2) #generates random numbers between 0,1
random_array

array([[4.17022005e-01, 7.20324493e-01],
       [1.14374817e-04, 3.02332573e-01],
       [1.46755891e-01, 9.23385948e-02],
       [1.86260211e-01, 3.45560727e-01],
       [3.96767474e-01, 5.38816734e-01]])

In [12]:
# Random numbers from a normal distrubution
np.random.seed(2)

normal_dist_array = np.random.randn(5,2) #random normal dist between 0,1 of dim(row=2, col=5)
print(normal_dist_array)


# Random numbers between a specific range
random_integers = np.random.randint(low=0, high=100, size=(5,2))  #random normal dist between 0,1 of dim(row=2, col=5) within a range0 to 100
print(random_integers)


[[-0.41675785 -0.05626683]
 [-2.1361961   1.64027081]
 [-1.79343559 -0.84174737]
 [ 0.50288142 -1.24528809]
 [-1.05795222 -0.90900761]]
[[37 39]
 [67  4]
 [42 51]
 [38 33]
 [58 67]]


## Element Wise Operations 
### Numpy excels in performing mathematical operations on arrays efficiently

In [15]:
# operations on entire arrays element by element

# arr = np.array([[2,3,4], [4,5,6]])

# first_row = arr[0]

# first_col = arr[:,0]

arr = arr + 1
print(arr)

arr = arr*2
print(arr)

# Similar operations for division and exponentiation


[[4 5 6]
 [7 8 9]]
[[ 8 10 12]
 [14 16 18]]


### Comparison Operators

#### We can perform element-wise comparisons and create boolean arrays:


In [22]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

greater_than_2 = arr1 > 2
print(greater_than_2)


print(arr1[greater_than_2])


print(arr1[arr1 > 1]) 

[1 2 3 4 5]
[False False  True  True  True]
[3 4 5]
[2 3 4 5]


### Logical Operators

## Summarizing Operations
### Numpy also provides functions for summarizing array data

In [24]:
min_value  = arr.min(); min_value

np.int64(8)

In [25]:
max_value = arr.max(); max_value

np.int64(18)

In [26]:
sum_value = arr.sum(); sum_value

np.int64(78)

In [27]:
mean_value = arr.mean(); mean_value

np.float64(13.0)

In [29]:
std_deviation = arr.std(); std_deviation

np.float64(3.415650255319866)